In [ ]:
import numpy as np

data = [1, 2, 3, 4, 5]
array = np.array(data)
array_size = np.size(array)  

print(array_size)  



In [13]:
arra5=np.ones((2,4))
print(arra5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
arra6 = np.arange(2,41,2)
print(arra6)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
